# fly.toml app configuration file generated for black-box on 2023-10-08T03:09:54-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "black-box"
primary_region = "dfw"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
